---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r,include = FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df %>% 
  count(tmax)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A - Scatterplot for Max/Min temperature

```{r}
weather_df %>% 
  mutate(text_label = str_c("Minimum Temp: ", tmin, "\nMaximum Temp: ", tmax)) %>% 
  plot_ly(x = ~tmin, y = ~tmax, color = ~name, text = ~text_label,
    alpha = .5, type = "scatter", mode = "markers")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B - Violin plot for min temperature

```{r}
weather_df %>% 
  plot_ly(
    y = ~tmin, x = ~name, color = ~name,
    type = "violin", colors = "viridis")
```

### Chart C - Histogram for max temperature

```{r}
weather_df %>% 
  plot_ly(x = ~tmax, color = ~name,
          type = "histogram", colors = "viridis")
```

### Chart D - Box plot for precipitation

```{r}
weather_df %>% 
  filter(prcp > 0) %>% 
  plot_ly(y = ~prcp, x = ~name, color = ~name,
          type = "box", colors = "viridis")
```